version: '3.7'

services:

  psql:
    container_name: psql
    image: postgres:13-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: airflow

volumes:
  psql_data: {}
